<?php $_tplvar = $this->getVars();?>

<style>
<!--
.container_24 {
	margin-left: auto;
	margin-right: auto;
/* 	width: 1170px; */
}
-->
</style>			
			<div id="page-content">
				<div id="content-container" class="container_24">
				    <div id="main-content" class="grid_16 push_10">
					<div class="main-content-padding">
	
							<div>
								<h3 style="margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
									Il Bucaneve s.r.l.
								</h3>
							</div>
						
							<h4>
								Il Bucaneve s.r.l. è un'azienda a conduzione familiare, che dal 2014 opera nel settore dell'ingrosso fiori in Umbria e nel Lazio offrendo la massima disponibilit&agrave;, competenza e professionalit&agrave; per tutti i suoi clienti.I nostri prodotti si distinguono per freschezza e qualit&agrave;, caratteristiche che ci rendono leader nel mercato floreale del centro Italia.
								<br><br>
								Importiamo ogni due giorni dai principali mercati Olandesi, Italiani, Sud Americani e Africani piante, fiori e bulbi di prima scelta in modo da offrire sempre prodotti freschi.
								<br><br>Uno nostro addetto alle vendite è sempre presente nella sede espositiva dove i clienti si possono recare per verificare il vasto assortimento.Da quest'anno, inoltre, è stato attivato il servizio di vendita online dando la possibilit&agrave; di ordinare direttamente dal nostro web-shop!I nostri corrieri, infine, consegnano tutti i giorni garantendo un servizio veloce, completo ed efficace.
								<br><br><br>
								Vieni a trovarci! 
							</h4>
							<div class="clear"></div>
						</div>
					</div>
				</div>
			</div>