<?php $_tplvar = $this->getVars();?>

<style>
<!--
.container_24 {
	margin-left: auto;
	margin-right: auto;
/* 	width: 1170px; */
}
-->
</style>			
			<div id="page-content">
				<div id="content-container" class="container_24">
				    <div id="main-content" class="grid_16 push_10"  style="float: left;width: 30%;">
					<div class="main-content-padding">
	
					<div>
						<h3 style="font-size: 2.35em;margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
							Contatti
						</h3>
					</div>

					<!-- Siamo in Corso Allamano, 61 a Grugliasco, a poca distanza dalla zona commerciale Le Gru, aperti tutti i giorni dalle 9 alle 19.30. -->
					
					<div class="clear"></div>
					<div id="contactInfo">
						<div class="grid_4 contactFieldDesc">Indirizzo:</div>
						<div class="grid_11 contactFieldValue">Via Maestri del lavoro</div>
						<div class="clear"></div>
						<div class="grid_4 contactFieldDesc"></div>
						<div class="grid_11 contactFieldValue">05100 Terni</div>
						<div class="clear"></div>
						<div class="grid_4 contactFieldDesc"></div>
						<div class="grid_11 contactFieldValue">Coordinate Geografiche: 45.0522777 - 7.5861606,17</div>
						<div class="clear"></div>
						<div class="grid_4 contactFieldDesc">Telefono:</div>
						<div class="grid_11 contactFieldValue">(+39) 3337819635</div>
						<div class="clear"></div>
						<div class="grid_4 contactFieldDesc">Telefono:</div>
						<div class="grid_11 contactFieldValue">(+39) 3408728035</div>
						<div class="grid_4 contactFieldDesc">Email:</div>
						<div class="grid_11 contactFieldValue"></div>
						
						
						<div class="clear"></div>
					</div>
					<div class="clear"></div>

					
					<div>
						<h3 style="font-size: 2.35em;margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
							Orari di Apertura:
						</h3>
					</div>
					<div class="textwidget">
					
						<div style="float:left;width:200px">
							<strong>Dal Luned&iacute; alla Domenica:</strong><br />
							Dalle <em><strong>9:00</strong></em> alle <em><strong>19</strong></em><br />
						</div>

						<div class="clear"></div>
					</div>							
					
					
					<div id="contact-wrapper">
					
<!-- 
<?php					    // Message Area.  It shows a message upon successful email submission
					    if( isset( $emailSent ) && $emailSent == true ) : ?>
						<div class="success">
						    <div class="msg-box-icon">
							<strong>Email Successfully Sent!</strong><br />
							Thank you <strong><?php echo $contact_name_thx; ?></strong> for using our contact form! Your email was successfully sent and we will be in touch with you shortly.
						    </div>
						</div>
<?php					    elseif ( isset( $emailSent ) && $emailSent == false ) : ?>
						<div class="erroneous">
						    <div class="msg-box-icon">
							Failed to connect to mailserver!
						    </div>
						</div>
<?php					    endif; ?>
					    <form id="contactForm" class="cmxform" method="post" action="#contact-wrapper">
						<strong>Utilizza il form sottostante per inviarci una mail:</strong>
						<div>
						    <label for="contact_name">Nome </label><em>(obbligatorio, almeno 2 caratteri)</em><br />
						    <input id="contact_name" name="contact_name" size="30" class="required<?php if(isset($nameError)) echo ' error'; ?>" value="<?php echo htmlentities($contact_name, ENT_QUOTES, "UTF-8"); ?>" />
<?php						    if(isset($nameError)) echo '<label class="error" for="contact_name" generated="true">'.$nameError.'</label>'; ?>
						</div>
						<div>
						    <label for="contact_email">E-Mail </label><em>(obbligatorio)</em><br />
						    <input id="contact_email" name="contact_email" size="30"  class="required email<?php if(isset($emailError)) echo ' error'; ?>" value="<?php echo htmlentities($contact_email, ENT_QUOTES, "UTF-8"); ?>" />
<?php						    if(isset($emailError)) echo '<label class="error" for="contact_email" generated="true">'.$emailError.'</label>'; ?>
						</div>
						<div>
						    <label for="contact_phone">Telefono </label><em>(opzionale)</em><br />
						    <input id="contact_phone<?php echo $NA_phone_format; ?>" name="contact_phone<?php echo $NA_phone_format; ?>" size="14" class="phone<?php if(isset($phoneError)) echo ' error'; ?>" value="<?php echo htmlentities($contact_phone, ENT_QUOTES, "UTF-8"); ?>" maxlength="14" />
						    <label for="contact_ext">ext. </label>
						    <input id="contact_ext<?php echo $NA_phone_format; ?>" name="contact_ext<?php echo $NA_phone_format; ?>" size="5" class="ext<?php if(isset($extError)) echo ' error'; ?>" value="<?php echo htmlentities($contact_ext, ENT_QUOTES, "UTF-8"); ?>" maxlength="5" />
<?php						    if(isset($phone_extError)) echo '<label class="error" for="contact_phone" generated="true">'.$phone_extError.'</label>'; ?>
						</div>
						<div>
						    <label for="contact_message">Commento </label><em>(obbligatorio)</em><br />
						    <textarea id="contact_message" name="contact_message" cols="70" rows="7" class="required<?php if(isset($messageError)) echo ' error'; ?>"><?php echo htmlentities($contact_message, ENT_QUOTES, "UTF-8"); ?></textarea>
<?php						    if(isset($messageError)) echo '<br /><label class="error" for="contact_message" generated="true">'.$messageError.'</label>'; ?>
						</div>

<?php						if ( $recaptcha_enabled == 'yes' ) : ?>
						    <script type="text/javascript">var RecaptchaOptions = {theme : '<?php echo $recaptcha_theme; ?>', lang : '<?php echo $recaptcha_lang; ?>'};</script>
						    <div>
<?php							echo recaptcha_get_html( $publickey, $rCaptcha_error ); ?>
						    </div>
<?php						endif; ?>

						<div>
						    <input name="submit" class="submit" type="submit" value="Invia Richiesta"/>
						</div>
					    </form>
						-->
					</div><!-- end contact-wrapper -->
					</div><!-- end main-content-padding -->
				    </div><!-- end main-content -->
				    
				    
				    
					<div  style="float: left;width: 70%;">
						<h3 style="font-size: 2.35em;margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
							Richiesta Informazioni
						</h3>
					</div>
					<div id="contactInfo" style="float: left;width: 70%;">
						
						<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=RequestInfo" method="post" onsubmit="javascript:return validateForm();">
						
						<table width="100%">
						<tr>
							<td width="20%" style="padding:10px">Nome:</td>
							<td style="padding:10px"><input type="text" name="nome" style="padding:5px;width:100%"></td>
						</tr>
						<tr>
							<td width="20%" style="padding:10px">Cognome:</td>
							<td style="padding:10px"><input type="text" name="cognome" style="padding:5px;width:100%"></td>
						</tr>
						<tr>
							<td width="20%" style="padding:10px">Telefono:</td>
							<td style="padding:10px"><input type="text" name="telefono" style="padding:5px;width:100%"></td>
						</tr>
						<tr>
							<td width="20%" style="padding:10px">Cellulare:</td>
							<td style="padding:10px"><input type="text" name="cellulare" style="padding:5px;width:100%"></td>
						</tr>
						<tr>
							<td width="20%" style="padding:10px">Indirizzo (Via, Citt&agrave;,Provincia)&nbsp;:</td>
							<td style="padding:10px"><input type="text" name="indirizzo" style="padding:5px;width:100%"></td>
						</tr>
						
						<tr>
							<td width="20%" style="padding:10px">Email: (*)</td>
							<td style="padding:10px"><input type="text" name="email" id="email" style="padding:5px;width:100%"></td>
						</tr>
						<tr>
							<td width="20%" style="padding:10px">Messaggio: (*)</td>
							<td style="padding:10px"><textarea name="note" cols="110" rows="6" style="width:100%" id="richiesta"></textarea></td>
						</tr>
						
						<tr>
							<td>Compila il codice captcha</th>
							<td align="left" style="padding:10px;">
								<script type="text/javascript">
								var RecaptchaOptions = {
									theme : 'blackglass'
								};
								</script>		
								<script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=<?php echo GOOGLE_RECAPCHA_PUBLIC_KEY;?>"></script>
								<noscript>
								<iframe src="http://www.google.com/recaptcha/api/noscript?k=<?php echo GOOGLE_RECAPCHA_PUBLIC_KEY;?>" height="300" width="500" frameborder="0"></iframe><br>
								<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
								<input type="hidden" name="recaptcha_response_field" value="manual_challenge">
								</noscript>
							</td>
						</tr>
						<?php if($_REQUEST['error_captcha']):?>
						<tr>
							<th colspan="2" style="color:red;padding:6px;">Attenzione errore nell'inserimento del Captcha</th>
						</tr>
						<?php endif;?>
						<tr>
							<td>(*) Campi obbligatori</td>
							<td><button type="submit" title="Invia Richiesta" class="button btn-cart"><span><span>Invia Richiesta</span> </span></button></td>
						</tr>
						<?php if($_REQUEST['confirm']):?>
						<tr>
							<th colspan="2" style="color:green;padding:6px;">La tua richiesta &egrave; stata inviata correttamente</th>
						</tr>
						<?php endif;?>
						
						
						</table>
						
						</form>						
						<div class="clear"></div>
					</div>				    
				    
					<script type="text/javascript">
					<!--
					function validateForm()
					{
						var email = jQuery('#email').val();
						var richiesta = jQuery('#richiesta').val();
						var captcha_code = jQuery('#captcha_code').val();
						var ret = true;
						
						if(email == '')
						{
							jQuery('#email').css('border', '1px solid red');
							ret = false;
						}
						else
							$('#email').css('border', '#555555');
						if(richiesta == '')
						{
							jQuery('#richiesta').css('border', '1px solid red');
							ret = false;
						}
						else
							jQuery('#richiesta').css('border', '#555555');
					
						return ret;
					}
					//-->
					</script>				    
				    
				    
				    <div class="clear"></div><div class="clear"></div>
					<div style="text-align: center;">
						<h3 style="font-size: 2.35em;margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
							Google Map
						</h3>
					</div>
				    
					<div id="sidebar" class="grid_8 pull_16 sidebar-box">
						<div id="sidebarSubnav">
							<div id="googlemap-widget" class="substitute_widget_class">
								<br>
								<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2939.2679070331164!2d12.603473215462285!3d42.54960387917465!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132ee35a4bd7dacf%3A0xd8953b127830e!2sVia+Maestri+del+Lavoro%2C+05100+Terni+TR!5e0!3m2!1sit!2sit!4v1467018443635" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>							    
							</div>
						</div>
						<!-- end sidebarSubnav -->
					</div>
					<!-- end sidebar -->
				</div>
				<!-- end content-container -->
				<div class="clear"></div>
				<!-- END -->
				
			</div>