<?php
$_tplvar = $this->getVars();
?>

						<div id="header" class="fix">
							<div class="headline">
								<a title="Tangando" href="<?php echo $_tplvar['SITE_ROOT'];?>" class="home">
									<img alt="Tangando" src="<?php echo $_tplvar['SITE_ROOT'];?>img/web/logo.png" width="150">
								</a>
								<div class="header-text">
									Associazione Culturale Tangando
								</div>
							</div>
						</div>
