<?php
$_tplvar = $this->getVars();
?>
						<br>
						<p style="font-size: 13px; color:#fff; margin: 0; padding: 0; font-family: Helvetica, Arial, sans-serif;">
						Per non ricevere la Newsletter di Tangando, <a href="'.WWW_ROOT.'?act=NewsletterSubscribe&remove=1&email='.$email.'">cliccare qui</a>.
                        </p>
						<br>
						<p style="font-size: 13px; color:#fff; margin: 0; padding: 0; font-family: Helvetica, Arial, sans-serif;">
                        Associazione Culturale Tangando - Telefono 339 8461340 - Email info@tangando.it - Sede Corsi CENTRO "CSERDI" DI VIA DON MILANI, 1 Monterotondo (RM)
                        </p>                        