<?php
$_tplvar = $this->getVars();
$this->getIntlPartial('Index');
?>
<p class="empty"><?php echo $this->getTranslation('Hai aggiunto');?> <?php echo count($_SESSION[session_id()]['basket'])?> <?php echo $this->getTranslation('prodotto/i');?></p>
<ol id="cart-sidebar" class="mini-products-list">
	<?php 
	
	$session = $_SESSION[session_id()]['basket'];
	unset($session['n_carrelli']);
	unset($session['perc_occupazione']);
	
	foreach($session as $prod):?>
	<li class="item last odd">
		<a href="javascript:void(0);" title="Htc Mobile 1120" class="product-image">
			<?php $image = $this->getImageFromVbn($prod['giacenza']['vbn']);?>
			
			<?php
			if(!empty($prod['giacenza']))
				$bar_code = $prod['giacenza']['bar_code'];
			else
				$bar_code = $prod['contenuto']['vbn']['vbn'];
			?>			

			<?php $content = $this->getContentById($prod['giacenza']['id_content']);?>

			<?php $image = null;?>
			<?php $vbn_image = $this->getImageFromVbn($content['vbn']);?>
				<?php $obj_image = $this->dbGetImageFromBarCode($bar_code);?>
				<?php $product_image = $this->dbGetImageProductFromBarCode($bar_code);?>
				<?php if(!empty($obj_image)):?>
					<?php $image = $obj_image[0]['www_path'].$obj_image[0]['name'];?>
				<?php elseif(!empty($product_image)):?>
					<?php $image = $product_image;?>
				<?php else:?>
				<?php $image = null;?>
				<?php endif;?>
				<?php if(!empty($image)):?>
					<img class="firstImg" src="<?php echo $image?>" alt="" />
				<?php else:?>
					<?php if(!empty($vbn_image)):?>
							<img id="image_custom" src="<?php echo $vbn_image?>" alt="" style="width:40px;height:40px;" width="220" height="200" oncontextmenu="return false;"/>
					<?php endif;?>
					<?php if (empty($image) && empty($vbn_image)):?>
						<img src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/image_large.gif" width="40" height="40">
					<?php endif;?>
				<?php endif;?>	
		</a>			
		<div class="product-details">
<?php if ($_SESSION['LoggedUser']['username'] == 'siso'):?>
<?php 
//_dump($prod);
?>
<?php endif;?>
		
			<a href="<?php echo $_tplvar['WWW_ROOT']?>?act=ShoppingCart&delete=1&delete_from_box=1&id_content=<?php echo $prod['contenuto']['id']?>&id_magazzino=<?php echo $prod['giacenza']['id']?>" title="<?php echo $this->getTranslation('Rimuovi');?>" onclick="return confirm('<?php echo $this->getTranslation('Sei sicuro di voler rimuovere il prodotto selezionato');?>?');" class="btn-remove">
				<?php echo $this->getTranslation('Rimuovi');?>
			</a>
			<!-- <a href="http://devthemes.org/megashop/index.php/checkout/cart/configure/id/6276/?___SID=U" title="Edit item" class="btn-edit"><?php echo $this->getTranslation('Modifica');?></a> -->
			<p class="product-name"><a href="javascript:void(0);"><?php echo $prod['contenuto']['nome_it'].' '.$prod['contenuto']['descrizione_it']?></a></p>
			<strong><?php echo $prod['giacenza']['quantita']?></strong> x <strong><?php echo $prod['basket_qty']['sel_quantita']?></strong> 
			<span class="price">
				<?php echo Currency::FormatEuro(($prod['giacenza'][$_tplvar['key_prezzo']]*$prod['basket_qty']['sel_quantita']))?>
				<?php $tot_price = $tot_price + str_replace(',', '.',($prod['giacenza'][$_tplvar['key_prezzo']]*$prod['basket_qty']['sel_quantita']));?>
			</span>
			<div class="truncated">
				<div class="truncated_full_value">
					<dl class="item-options">
						<?php if(!empty($prod['giacenza']['vbn'])):?>
							<dt><?php echo $this->getTranslation('VBN');?></dt>
							<dd><?php echo $prod['giacenza']['vbn']?></dd>
						<?php endif;?>						
						<?php if(!empty($prod['giacenza']['descrizione'])):?>
							<dt><?php echo $this->getTranslation('Nome');?></dt>
							<dd><?php echo $prod['giacenza']['descrizione']?></dd>
						<?php endif;?>						
						<?php if(!empty($prod['giacenza']['C4'])):?>
							<dt><?php echo $this->getTranslation('Altezza');?></dt>
							<dd><?php echo $prod['giacenza']['C4']?></dd>
						<?php endif;?>						
						<?php if(!empty($prod['giacenza']['dimensione'])):?>
							<dt><?php echo $this->getTranslation('Dimensione');?></dt>
							<dd><?php echo $prod['giacenza']['dimensione']?></dd>
						<?php endif;?>						
						<?php if(!empty($prod['giacenza']['C5'])):?>
							<dt><?php echo $this->getTranslation('Provenienza');?></dt>
							<dd><?php echo $prod['giacenza']['C5']?></dd>
						<?php endif;?>						
						<?php if(!empty($prod['giacenza']['scelta'])):?>
							<dt><?php echo $this->getTranslation('Scelta');?></dt>
							<dd><?php echo $prod['giacenza']['scelta']?></dd>
						<?php endif;?>
						<?php if(!empty($prod['giacenza']['fusto'])):?>
							<dt><?php echo $this->getTranslation('Fusto');?></dt>
							<dd><?php echo $prod['giacenza']['fusto']?></dd>
						<?php endif;?>
					</dl>
				</div>
				<a href="#" onclick="return false;" class="details"><?php echo $this->getTranslation('Dettaglio');?></a>
			</div>
		</div>
	</li>
	<?php endforeach;?>
</ol>
<div class="actions_checkout">
	<p class="subtotal">
	<span class="label">Total:</span> <span class="price"><?php echo Currency::FormatEuro($tot_price)?></span>                                                </p>
	<button type="button" title="Checkout" class="button" onclick="setLocation('<?php echo $_tplvar['WWW_ROOT']?>?act=ShoppingCart')"><span><span><?php echo $this->getTranslation('Vai in cassa');?></span></span></button>
</div>
