<?php  

//$route = $_tplvar['WWW_ROOT'].$_SERVER['REQUEST_URI'];

$_tplvar = $this->getVars();
if(!empty($assign['keys_search']))
	$key_search = $assign['keys_search'];
	
// if(!empty($assign['order_by']))
// 	$orderBy = '&order_by='.$assign['order_by'];
// if(!empty($assign['order_type']))
// 	$orderType = '&order_type='.$assign['order_type'];
	
// if(!empty($route))
// 	$pagingUrl = $route.'&pageID='.$orderBy.$orderType;
// else 
	$pagingUrl = $_tplvar['WWW_ROOT'].'?act='.$_REQUEST['act'].$key_search.$orderBy.$orderType.'&pageID=';

$numViewPages = $_tplvar['numViewPage'];
$initPages 	  = $_tplvar['curr_page'] - $numViewPages;
?>
<?php //if($_tplvar['last_page'] > 1):?>
<div style="padding:6px;float:right;width:160px;">
<!-- 
		<span><?php echo $this->getText('prefix_paging_row_for_page');?></span>
		<span><?php if($assign['show_combo_row_page']) echo $this->getPartial('shared/ComboRowForPage');?></span>
		<span><?php echo $this->getText('suffix_paging_row_for_page');?></span>
 -->
</div>
<div class="pager">
    <div class="pages">
		<span>Pagina <?php echo $_tplvar['curr_page'];?> di <?php echo $_tplvar['last_page']?></span>&nbsp;&nbsp;

		<ol>
			<?php if($_tplvar['last_page'] > 1 && $_REQUEST['pageID'] > 1):?>
				<li><a href="<?php echo $pagingUrl;?><?php echo 1;?>">&laquo;</a></li>
			<?php endif;?>
			<?php 
				$j = 0;	
				for($i=$initPages;$i <= $_tplvar['tot_items'];$i++):
			?>
				<?php if($j <= ($numViewPages+$numViewPages) && $i > 0 && $j > 0):?>
				
					<?php if($i == $_tplvar['curr_page']):?>
						<li class="current"><?php echo $i;?></li>
					<?php else:?>
						<?php if($_tplvar['last_page'] > 1 && $i <= $_tplvar['last_page']):?>
						<li><a href="<?php echo $pagingUrl;?><?php echo $i;?>"><?php echo $i;?></a></li>
						<?php endif;?>
					<?php endif;?>
					
				<?php endif;?>
			<?php 
				$j++;
				endfor;
			?>	
			<?php if($_tplvar['last_page'] > 1 && $_REQUEST['pageID'] < $_tplvar['last_page']):?>
				<li><a href="<?php echo $pagingUrl;?><?php echo $_tplvar['last_page']?>">&raquo;</a></li>
			<?php endif;?>
			</li>
		</ol>		
    </div>
</div>