<?php
$_tplvar = $this->getVars();
?>
 <html lang="en">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <title>Associazione Culturale Tangando</title>

  </head>


<body bgcolor="#000000" cellpadding="0" cellspacing="0">

<form action="<?php echo $_tplvar['WWW_ROOT'];?>?act=Newsletter" method="post">
<input type="hidden" name="step" value="1">
    <table align="center">
    <tr>
    	<td><div><input class="submit" type="submit" value="Avanti" /></div></td>
    	<td><div><input class="submit" type="button" value="Lista Newsletter" onclick="javascript:window.location.href='<?php echo $_tplvar['WWW_ROOT'];?>?act=Newsletter&search=1'"/></div></td>
    </tr>
    </table>

    
  		<table cellpadding="0" cellspacing="0" border="0" align="center" width="500">
		  <tr>
		  	<td align="center" style="border:1px solid #ffffff">
		  	
				<table border="0" width="600" cellpadding="0" cellspacing="0"> 
				<tr> 
				    <td valign="middle"> 
				    
						<?php $this->getPartial('shared/MenuTop');?>

				    </td> 
				    <td valign="middle" bgcolor="#9C8460" align="right"> 
				    	<!-- loginbox //--> 
					</td> 
				</tr> 
				</table> 
                
				<table cellpadding="0" cellspacing="0" border="0" align="center" width="600" style="font-family: Helvetica, Arial, sans-serif; background-color:#fff;" bgcolor="#fff">
			      	
					<tr>
					<!-- contenuto -->
			        	<td width="580" valign="top" align="left" bgcolor="#fff" style="font-family: Helvetica, Arial, sans-serif; font-size:12px; padding: 25px 0 0; background-color:#fff;" class="content">
							<table cellpadding="0" cellspacing="0" border="0"  style="color: #717171; font: normal 12px Helvetica, Arial, sans-serif; margin: 0; padding: 0;" width="580">
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 0;  font-family: Helvetica, Arial, sans-serif; background: url(|WWW_ROOT|newsletter/images/bg_date.png) no-repeat left top; height:20px; line-height: 20px;" align="center" width="550" height="20" background="|WWW_ROOT|newsletter/images/bg_date.png">
									<!--<h3 style="color:#666; font-weight: bold; text-transform: uppercase; margin: 0; padding: 0; line-height: 10px; font-size: 10px;"><$currentdayname$> <$currentday$> <$currentmonthname$></h3>-->
                                    
                                    <h3 style="color:#ffffff; font-weight: bold; text-transform: uppercase; margin: 0; padding: 0; line-height: 10px; font-size: 10px;text-align:center;"><?php echo str_replace('ì', '&igrave;', strftime("%A %d %B %Y"));?></h3>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 20px 0 0;" align="left">			
									<h2 style="color:#646464; font-weight: bold; margin: 0; padding: 0; line-height: 26px; font-size: 18px; font-family: Helvetica, Arial, sans-serif; ">
<input type="text" name="titolo_0" value="<?php echo !empty($_tplvar['titolo'])? $_tplvar['titolo']: 'Titolo News';?>" onclick="this.value = ''" style="width:550px">
									</h2>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 10px 0 8px; background-color:#fff; font-size:14px;"  valign="top" bgcolor="#fff">
									<p style="color:#767676; font-weight: normal; margin: 0; padding: 0; line-height: 20px; font-size: 13px;font-family: Helvetica, Arial, sans-serif; background-color:#fff;">


<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'];?>js/mootools.core.js"></script>
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'];?>js/mootools.more.js"></script>
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'];?>js/mootools/DatePicker.js"></script>
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'];?>js/unFocus-History-p.js"></script>	
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckeditor.js"></script>

<div id="inserisci_newsletter" style="background-color:#fff;padding:30px"> 

		<div style="clear:both">
			<textarea cols="80" id="news_0" name="news_0" rows="10"><?php echo !empty($_tplvar['news'])? $_tplvar['news']: '';?></textarea>
		</div>
</div>

            <script type="text/javascript">
            //<![CDATA[
		      CKEDITOR.replace( 'news_0',
		      {
		         filebrowserBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html',
		         filebrowserImageBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html?Type=Images',
		         filebrowserFlashBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html?Type=Flash',
		         filebrowserUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
		         filebrowserImageUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
		         filebrowserFlashUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
		         width : 500,
		      } 
			  );
            //]]>
            </script>


									</p>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>	

<?php 
foreach ($_tplvar['news_added'] as $key => $val):
if($key != 'index'):
?>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 8px 0;"  valign="top">
								<!--<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/img.jpg" style="border: 1px solid #e9e9e9; display: block;" border="1" alt="">-->
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 5px 0 5px;"  valign="top">
									<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/divider.png" alt="" style="border-top: 10px solid #fff">
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 15px 0 0;" align="left">			
									<h2 style="color:#646464; font-weight: bold; margin: 0; padding: 0; line-height: 26px; font-size: 18px; font-family: Helvetica, Arial, sans-serif; ">
<input type="text" name="titolo_<?php echo $key?>" value="<?php echo !empty($val['titolo']) ? $val['titolo'] : 'Titolo News'?>" onclick="this.value = ''" style="width:550px">
									</h2>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 10px 0 45px;"  valign="top">
									<table cellpadding="0" cellspacing="0" border="0"  style="color: #717171; font: normal 11px Helvetica, Arial, sans-serif; margin: 0; padding: 0;" width="369">
									<tr>
										<td valign="top" style="padding: 5px 0 7px 0px;">
										<!--<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/img2.jpg" style="border: 1px solid #e9e9e9; display: block;" border="1" alt="" align="right">-->
										</td>
									</tr>
									<tr>
										<td style="padding: 5px 0 7px 0px;"  valign="top" align="left">
											<p style="color:#767676; font-weight: normal; margin: 0; padding: 0; line-height: 20px; font-size: 13px;font-family: Helvetica, Arial, sans-serif;">

		<div id="inserisci_newsletter" style="background-color:#fff;padding:30px"> 
		
			<div style="clear:both">
				<textarea cols="80" id="news_<?php echo $key?>" name="news_<?php echo $key?>" rows="10"><?php echo !empty($val['news'])? $val['news']: '';?></textarea>
			</div>
		</div>

            <script type="text/javascript">
            //<![CDATA[
		      CKEDITOR.replace( 'news_<?php echo $key?>',
		      {
		         filebrowserBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html',
		         filebrowserImageBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html?Type=Images',
		         filebrowserFlashBrowseUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/ckfinder.html?Type=Flash',
		         filebrowserUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
		         filebrowserImageUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
		         filebrowserFlashUploadUrl : '<?php echo $_tplvar['WWW_ROOT'];?>js/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
		         width : 500,
		      } 
			  );
            //]]>
            </script>
								
											</p>
										</td>
									</tr>
									</table>
								</td>
							</tr>
<?php endif;?>
<?php endforeach;?>			
							<tr>
								<td colspan="3">
									<input class="submit" style="float: right;" type="submit" value="Avanti" />
									<input class="submit" style="float: right" type="submit" value="Rimuovi News" name="removeNews" />
									<input class="submit" style="float: right;" type="submit" value="Aggiungi News" name="addNews" />
								</td>
							</tr>
							</table>	
						</td>
			      </tr>
				  	<tr>
						<td width="600" align="left" style="padding: font-size: 0; line-height: 0; height: 3px;" height="3" colspan="2"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/bg_bottom.png" alt="header bg"></td>
				      </tr>	


				</table><!-- body -->
				<table cellpadding="0" cellspacing="0" border="0" align="center" width="600" style="font-family: Helvetica, Arial, sans-serif; line-height: 10px;" class="footer">
				<tr>
			        <td align="center" style="padding: 5px 0 10px; font-size: 11px; color:#fff; margin: 0; line-height: 1.2;font-family: Helvetica, Arial, sans-serif;" valign="top">
			        
						<?php $this->getPartial('shared/TermsConditionsBottom');?>
						
					</td>
			      </tr>
				</table><!-- footer-->
		  	</td>
		</tr>
    </table>
    <table align="center">
    <tr>
    	<td><div></div></td>
    </tr>
    </table>
</form>
</div>    
  </body>
</html>
