<?php
$_tplvar = $this->getVars();
?>
 <html lang="en">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <title>Associazione Culturale Tangando</title>
  </head>
  
<body bgcolor="#000000" cellpadding="0" cellspacing="0">

 <form action="<?php echo $_tplvar['WWW_ROOT'];?>?act=Newsletter" method="post">
<input type="hidden" name="step" value="2">
    <table align="center">
    <tr>
    	<td><div><input class="submit" type="button" value="Indietro" onclick="document.location.href = '<?php echo $_tplvar['WWW_ROOT'];?>?act=Newsletter'"/></div></td>
    	<td><div><input class="submit" type="submit" value="Avanti" /></div></td>
    </tr>
    </table>
  		<table cellpadding="0" cellspacing="0" border="0" align="center" width="500">
		  <tr>
		  	<td align="center" valign="top" style="border:1px solid #ffffff">
					<table border="0" width="500" align="center" cellspacing="0" cellpadding="0">  
					<tr> 
						<td colspan="2" valign="top"> 
							<table border="0" width="600" cellpadding="0" cellspacing="0"> 
							<tr> 
							    <td valign="middle"> 
							    
							    	<?php $this->getPartial('shared/MenuTop');?>
							    	
							    </td> 
							    <td valign="middle" bgcolor="#9C8460" align="right"> 
							    	<!-- loginbox //--> 
								</td> 
							</tr> 
							</table> 
						</td> 
					</tr> 
					</table> 

		  			<table cellpadding="0" cellspacing="0" border="0" align="center" width="600" style="font-family: Helvetica, Arial, sans-serif; background:url(<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/bg_table2.png) repeat-y;" bgcolor="#000000">
					<tr>
			        	<!-- contenuto -->
			        	<td width="580" valign="top" align="left" bgcolor="#000000" style="font-family: Helvetica, Arial, sans-serif; font-size:12px; padding: 25px 0 0; background-color:#fff;" class="content">
							<table cellpadding="0" cellspacing="0" border="0"  style="color: #717171; font: normal 11px Helvetica, Arial, sans-serif; margin: 0; padding: 0;" width="580">
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 0;  font-family: Helvetica, Arial, sans-serif; background: url(<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/bg_date.png) no-repeat left top; height:20px; line-height: 20px;" align="center" width="550" height="20" background="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/bg_date.png">
                                    <h3 style="color:#666; font-weight: bold; text-transform: uppercase; margin: 0; padding: 0; line-height: 10px; font-size: 10px;text-align:center;">
                                    <?php echo str_replace('ì', '&igrave;', strftime("%A %d %B %Y"));?>
                                    </h3>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 20px 0 0;" align="center">			
									<h2 style="color:#646464; font-weight: bold; margin: 0; padding: 0; line-height: 26px; font-size: 18px; font-family: Helvetica, Arial, sans-serif; ">
<?php echo $_tplvar['titolo'];?>
									</h2>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 10px 0 8px; background-color:#fff; font-size:14px;"  valign="top" bgcolor="#000000">
									<p style="color:#767676; font-weight: normal; margin: 0; padding: 0; line-height: 20px; font-size: 13px;font-family: Helvetica, Arial, sans-serif; background-color:#fff;">
<?php echo $_tplvar['news'];?>
									</p>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
<?php 
foreach ($_tplvar['news_added'] as $key => $val):
if($key != 'index'):
?>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 8px 0;"  valign="top">
								<!--<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/img.jpg" style="border: 1px solid #e9e9e9; display: block;" border="1" alt="">-->
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 5px 0 5px ;"  valign="top">
									<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/divider.png" alt="" style="border-top: 10px solid #fff">
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 15px 0 0;" align="left">			
									<h2 style="color:#646464; font-weight: bold; margin: 0; padding: 0; line-height: 26px; font-size: 18px; font-family: Helvetica, Arial, sans-serif; ">
<?php echo $val['titolo'];?>
									</h2>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
							<tr>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
								<td style="padding: 10px 0 45px;"  valign="top">
									<table cellpadding="0" cellspacing="0" border="0"  style="color: #717171; font: normal 11px Helvetica, Arial, sans-serif; margin: 0; padding: 0;" width="550">
									<tr>
										<td style="padding: 5px 0 7px 0px;"  valign="top" align="left">
											<p style="color:#767676; font-weight: normal; margin: 0; padding: 0; line-height: 20px; font-size: 13px;font-family: Helvetica, Arial, sans-serif;">
<?php echo $val['news'];?>										
											</p>
										</td>
										<td valign="top" style="padding: 5px 0 7px 0px;">
										<!--<img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/img2.jpg" style="border: 1px solid #e9e9e9; display: block;" border="1" alt="" align="right">-->
										</td>
									</tr>
									</table>
								</td>
								<td width="22" style="font-size: 1px; line-height: 1px;"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/spacer.gif" alt="space" width="20"></td>
							</tr>
<?php endif;?>
<?php endforeach;?>							
							</table>	
						</td>
					
			      </tr>
				  	<tr>
						<td width="600" align="left" style="padding: font-size: 0; line-height: 0; height: 3px;" height="3" colspan="2"><img src="<?php echo $_tplvar['WWW_ROOT'];?>newsletter/images/bg_bottom.png" alt="header bg"></td>
				      </tr>	
				</table><!-- body -->
				<table cellpadding="0" cellspacing="0" border="0" align="center" width="600" style="font-family: Helvetica, Arial, sans-serif; line-height: 10px;" class="footer">
				<tr>
			        <td align="center" style="padding: 5px 0 10px; font-size: 11px; color:#fff; margin: 0; line-height: 1.2;font-family: Helvetica, Arial, sans-serif;" valign="top">

						<?php $this->getPartial('shared/TermsConditionsBottom');?>

					</td>
			      </tr>
				</table><!-- footer-->
		  	</td>
		</tr>
    </table>
    <table align="center">
    <tr>
    	<td><div><input class="submit" style="float: right;" type="button" value="Indietro" onclick="document.location.href = '<?php echo $_tplvar['WWW_ROOT'];?>?act=Newsletter'"/></div></td>
    	<td><div><input class="submit" style="float: right;" type="submit" value="Avanti" /></div></td>
    </tr>
    </table>
    
</form>
</div>    
  </body>
</html>
