<?php $_tplvar = $this->getVars();?>
	<div id="top-container" class="container_24">
		<div class="clear"></div>
		<div id="top" class="grid_24">
			<div id="logo" class="grid_14">
				<h1>
					<a href="<?php echo $_tplvar['WWW_ROOT']?>" class="pngfix" style="background: transparent url( <?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/logo.png ) no-repeat 0 100%; width:600px; height:90px;"></a>
				</h1>
			</div>
			<div id="slogan" class="grid_17" style="top:70px; left:100px;"><!-- Slogan --></div>
			<!-- end logo slogan -->
			<div id="search" class="grid_7 prefix_17">
				<h2>Amministrazione</h2>
			</div>
			<!-- end search -->
			<div class="phone-number grid_7 prefix_17"><!-- Info --></div>
			<!-- end top-icons -->
		</div>
		<!-- end top -->
	</div>